# Redirect all requests to remzi.netlify.app, cavdar.nl, www.cavdar.nl, and www.remzi.info to remzi.info
[[redirects]]
from = "https://www.remzi.info/*"
to = "https://remzi.info/:splat"
status = 301

[[redirects]]
from = "https://remzi.netlify.app/*"
to = "https://remzi.info/:splat"
status = 301

[[redirects]]
from = "https://cavdar.nl/*"
to = "https://remzi.info/:splat"
status = 301

[[redirects]]
from = "https://www.cavdar.nl/*"
to = "https://remzi.info/:splat"
status = 301

# Simple Analytics proxy - https://docs.simpleanalytics.com/proxy
[[redirects]]
from = "/proxy.js"
to = "https://simpleanalyticsexternal.com/proxy.js?hostname=remzi.info&path=/simple"
status = 200

[[redirects]]
from = "/simple/*"
to = "https://queue.simpleanalyticscdn.com/:splat"
status = 200

# Redirects
[[redirects]]
from = "/assets/cv.pdf"
to = "/cv"
status = 301

[[redirects]]
from = "/cv.html"
to = "/cv"
status = 301

[[redirects]]
from = "/index.php"
to = "/"
status = 301

[[redirects]]
from = "/assets/Onderzoeksverslag-van-R.Cavdar-20-01-2023.pdf"
to = "https://storage.remzi.info/assets/docs/Onderzoeksverslag-van-R.Cavdar-20-01-2023.pdf"
status = 301

# Default favicon redirect
[[redirects]]
from = "/favicon.ico"
to = "https://storage.remzi.info/assets/images/logo.png"
status = 301

# Pages
[[redirects]]
from = "/"
to = "/index.html"
status = 200

[[redirects]]
from = "/portfolio"
to = "/index.html"
status = 200

[[redirects]]
from = "/cv"
to = "/index.html"
status = 200

# 404
[[redirects]]
from = "/*"
to = "/index.html"
status = 404